supportpal/api-client-php

.github/workflows/ci.yml, phpunit.xml.dist, src/Cache/ApiCacheMap.php, src/Cache/CacheStrategyConfigurator.php, src/Cache/CacheableRequestMatcher.php, src/Dictionary/ApiDictionary.php, src/SupportPal.php, test/Cache/CacheableApisTest.php, test/ContainerAwareBaseTestCase.php, test/Functional/Api/Cache/CacheableApisTest.php, test/Integration/Factory/RequestFactoryTest.php, test/Resources/services_test.yml, test/Unit/Cache/ApiCacheMapTest.php, test/Unit/Cache/CacheStrategyConfiguratorTest.php, test/Unit/Cache/CacheableRequestMatcherTest.php
The fix offloads handling the BASE url to only the single added const.
=> Fix: #38, 37 Update api prefix handling

src/Model/Shared/Option.php
The order column on all `*_option` tables is nullable:
```sql
CREATE TABLE `user_customfield_option` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`field_id` int(10) unsigned NOT NULL,
`order` int(10) unsigned DEFAULT NULL,
`value` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
`created_at` int(11) NOT NULL,
`updated_at` int(11) NOT NULL DEFAULT 0,
PRIMARY KEY (`id`),
KEY `user_customfield_option_field_id_foreign` (`field_id`),
CONSTRAINT `user_customfield_option_field_id_foreign` FOREIGN KEY (`field_id`) REFERENCES `user_customfield` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
```
=> fix: nullable order attribute on custom field options

src/Config/ApiContext.php, src/Config/RequestDefaults.php, test/Unit/Config/ApiContextTest.php
The API context currently defaults to `https` connections.
If you want to switch to `http` you have to:
```php
$context->setScheme('http')->setPort(80);
```
This is somewhat tedious and unnecessary:
1. The scheme is always either `http` or `https` so this abstraction (`setScheme`) is unnecessary
2. In the vast majority of situations the help desk is available on the world wide web (either port `80` / `443`) rather than some custom port.
This PR simplifies this use case to:
```php
$context->disableSsl();
```
I've also changed `disableSsl` in the `RequestDefaults` to `disableSslVerification` in order to prevent confusion. One pertains to the the URI, the other to request verification.
=> feat: added new ssl methods

src/Config/ApiContext.php, test/Unit/Config/ApiContextTest.php
This will save people a lot of heart ache. 
The WHMCS integration is a prime example where we have a URL and need to initialise the client. This occurs in two places:
1. initialisation of all api calls
2. validate.php
Very similar code is also used in the test suite... a lot of duplication that could be included in this library.
=> feat: create api context from url

src/Model/Ticket/SlaPlan.php
I haven't bothered to identify the steps required to replicate this but it occurs when submitting a ticket and also when viewing `supporttickets.php`. The error is fairly obvious, `SlaPlan` does not have an `id` attribute defined and so the type extractor is returning no data.
```
TypeError: array_filter() expects parameter 1 to be array, null given in /home/kieran/Websites/whmcs8/modules/support/supportpal/vendor/supportpal/api-client-php/src/Transformer/IntToBooleanTransformer.php:54
Stack trace:
#0 /home/kieran/Websites/whmcs8/modules/support/supportpal/vendor/supportpal/api-client-php/src/Transformer/IntToBooleanTransformer.php(54): array_filter(NULL, Object(Closure))
#1 /home/kieran/Websites/whmcs8/modules/support/supportpal/vendor/supportpal/api-client-php/src/Transformer/IntToBoolea …
```
=> fix: id attribute missing from SlaPlan model

src/Model/SettingsModel.php, src/Model/Shared/Settings.php, test/TestCase.php, test/Unit/Model/Shared/SettingsTest.php
Consider:
```php
$api = new SupportPal(new ApiContext('example.com', 'foo'));
$settings = $api->getCoreApi()->getSettings()->getSettings();
```
This isn't very easy to understand, why is `getSettings` being called twice. This PR changes it to:
```php
$api = new SupportPal(new ApiContext('example.com', 'foo'));
$settings = $api->getCoreApi()->getSettings()->all();
```
`toArray` may also be suitable instead of `all`
=> feat: renamed getSettings to all

phpstan.neon
Fixes:
```
Reached internal errors count limit of 50, exiting...                      
Internal error: Child process timed out after 60.0 seconds. Try making it  
longer with parallel.processTimeout setting.              
```
=> chore(phpstan): increased processTimeout

src/Exception/UndefinedPropertyException.php, src/Transformer/IntToBooleanTransformer.php, test/Unit/Transformer/IntToBooleanTransformerTest.php
When type extractor cannot identify the type, process and empty array so the SDK doesn't crash.
This fixes the following issue:
```
ERROR: TypeError: array_filter() expects parameter 1 to be array, null given in / supportpal/api-client-php/src/Transformer/IntToBooleanTransformer.php:54 Stack trace: #0
```
=> fix: skip conversion for non-identified types

src/Cache/CacheStrategyConfigurator.php
The goal of the PR is to add the `Authorization` header as part of the cache file keys. This ensures that if the header is changed, then files won't be served from cache for the same requests.
=> fix: add authorization header as part of cache file key

src/ApiClient.php, test/Integration/ApiClientTest.php, test/Unit/ApiClientTest.php
Nonencodeable exception will almost always return an error related to the parsing operation instead of the API response. This changes the behaviour to fetch the error from the response.
=> fix: use response reason phrase for non-json responses

composer.json
Nothing special in this. `else if` will raise an error when previously it didn't. This change doesn't affect this library.
=> chore(deps): updated supportpal/coding-standard to v0.3.0

.gitattributes, .github/dependabot.yml, .github/workflows/release.yml, .releaserc, package-lock.json, package.json
This repository is setup to require:
* PRs. You cannot push directly to `dev-master`
* semantic commits in PR titles
* squash & merge all PRs (no other options available)
* PR must be updated to `dev-master` (no need to rebase)
----
This PR adds semantic-release, which on every commit to `dev-master` will automatically:
* Create a new GitHub release (and Git tag)
* Generate a changelog
* Comment on linked issues and PRs saying they're released in a specific version
There are two benefits of this:
* automation - no need to manually tag releases
* releases correctly follow semantic versioning (so long as the PR author / reviewer, correctly set the title)
=> ci: added semantic-release

.github/dependabot.yml
Hopefully this enables semantic commits for dependabot updates, ref: https://dependabot.com/docs/config-file/#commit_message
=> ci: enable semantic commits in dependabot

.github/dependabot.yml
In classic fashion it turned out https://github.com/supportpal/api-client-php/pull/80 is the wrong syntax
https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates#commit-message is the correct syntax
=> ci: fix dependabot.yml syntax

composer.json
When running the SDK in production mode, the following exception would be thrown:
```
PHP Fatal error:  Uncaught LogicException: Unable to use the "Symfony\Component\PropertyInfo\Extractor\PhpDocExtractor" class as the "phpdocumentor/reflection-docblock" package is not installed. in /Users/ghaith/Documents/work_projects/SupportPal/supportpal-sdk/vendor/symfony/property-info/Extractor/PhpDocExtractor.php:63
```
This dependency was not met when installing production dependencies only. This behaviour is masked by phpunit requiring the same dependency in dev mode.
=> fix: add phpdocumentor production dependency

.gitattributes
* sorted the file alphabetically
* fixed `phpunit.dist.xml` reference, file is actually called `phpunit.xml.dist`
* fixed `package-lock.json` reference - missing `export-ignore`
* added new exclusions for `phpmd.xml`
=> fix: composer distribution file exclusions

src/Model/Department/Email.php
This PR adds 'string' type hint to Email. 
This is necessary because of the type validation pass the serializer does before committing the value through the setter.
The newly added type hint  just tells the serializer to expect a string, however we're enforcing that this string has a valid value in the setter.
=> fix: invalid department id type hint

src/Model/Department/Department.php
On the main helpdesk, the return of `default_assigned_to` attribute is an array of operators ID. the JSON response includes ids of operators instead of operators object, this PR corrects the type hint.
```
ERROR: TypeError: Argument 1 passed to SupportPal\\ApiClient\\Normalizer\\ModelNormalizer::applyAttributeAwareTransformations() must be of the type array, string given
...
```
=> fix: update department default assigned type hint

src/Factory/RequestFactory.php, test/Unit/Factory/RequestFactoryTest.php
This PR updates the order of variables in `array_merge` to overwrite values from the default values if also supplied in the function parameters.
> If the input arrays have the same string keys, then the later value for that key will overwrite the previous one. 
https://www.php.net/manual/en/function.array-merge.php
=> fix: unable to overwrite request defaults

src/Exception/InvalidDataException.php, src/Factory/BaseModelFactory.php, src/Factory/ModelFactory.php
In the case of having an issue with model deserialization, the data causing the issue can be lost. To have better logs, this PR adds the data into the thrown exception so SDK users would be able to log the data causing the issue.
=> feat: add array data to factory exception

src/Model/SelfService/CategoryTranslation.php, test/DataFixtures/SelfService/CategoryTranslationData.php, test/Unit/Model/Collection/CollectionTest.php
Calling `{server}/api/selfservice/category` returns the category response  reply:
```
...
"translations": [
{
"category_id": 1,
"name": "test",
"slug": "test",
"locale": "en"
}
...
```
The property `type_id`  is not valid in the context of category_translation and would throw an error when denormalizing the object. 
This PR  replaces the incorrect attribute.
=> fix: incorrect category translation attribute

src/SupportPal.php, test/Functional/SupportPalTest.php
In our code, we depend on Symfony's dependency injection library.  For example https://github.com/supportpal/api-client-php/blob/2fb1ba5dce125622c51365f9f1f233865258090e/src/Resources/factories.yml#L10 
This PR adds a function escapes '%' because Symfony dependency injection uses it to detect the value of the set parameter
=> fix: escape "%" in yaml parameters

src/Model/SelfService/TypeTranslation.php
Fixes:
```
`The type of the "slug" attribute for class "SupportPal\WhmcsIntegration\Vendor\SupportPal\ApiClient\Model\SelfService\TypeTranslation" must be one of "string" ("null" given).`
```
This can occur if you add a translation to an external link type. It now matches the same as the main type model.
=> fix: type translation slug can also be null

composer.json, composer.lock, src/Normalizer/ModelNormalizer.php
We're in the progress of upgrading our application to Laravel 10 and as such, require Symfony 6. This also switches two interfaces as the previous ones are deprecated by Symfony. The return type was a requirement as well. Without it, phpunit wouldn't pass.
Note: in my local environment E2E tests were failing, also for the main branch.
=> chore: update to symfony 6

composer.json, composer.lock, src/Model/SettingsModel.php, src/Model/Shared/Settings.php
CI runs: `composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress` which when using semantic versioning results in PHPStan being upgraded from the version in the lock file. PHPStan analysis tends to change every version so it's best if we lock it and manually upgrade, otherwise we're in a constantly battle fixing broken CI pipelines.
=> chore(deps): lock phpstan/phpstan to 1.10.25

composer.json, composer.lock, src/Cache/CacheStrategyConfigurator.php, src/Cache/SymfonyCacheStorage.php
`doctrine/cache` is deprecated and no longer maintained - https://www.doctrine-project.org/projects/doctrine-cache/en/current/index.html
`symfony/cache` seems like the easiest like for like replacement for our usage.
=> chore(deps): switch from doctrine/cache to symfony/cache
